### ISSUE TITLE
SystemError: <built-in function len> returned a result with an error set

### ISSUE THREAD

**Issue by ntelo007** [yxdragon/sknw#3]
Hi,

I am trying to run your demo ("Build graph") and I get the following error:

_pickle.UnpicklingError: invalid load key, 'O'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/.../sknw/demo.py", line 11, in <module>
    graph = sknw.build_sknw(ske)
  File "C:\Users\...\sknw-master\sknw\sknw.py", line 118, in build_sknw
    mark(buf)
  File "C:\Users\...\sknw-master\sknw\sknw.py", line 7, in neighbors
    dim = len(shape)
SystemError: <built-in function len> returned a result with an error set

I am using Windows 10, and I have installed the following packages in a venv:
![image](https://user-images.githubusercontent.com/31326655/69420549-360a1880-0d1f-11ea-80cb-b2bbf6c79f45.png)

**Comment by yxdragon** [comment]
It seems that numba has upgrade much, So I will review my code soon!

**Comment by ntelo007** [comment]
Which numba version should I use?

**Comment by yxdragon** [comment]
@ntelo007 now sknw can work with the new version numba, have a try!
